sudo: required

language: bash

services:
  - docker

script:
  - docker-compose build
  - docker-compose up -d
  - sh -c 'docker-compose exec master journalctl -f | grep -v kubelet-wrapper.sh | { sed "/Started Bootkube Kubernetes Bootstrap/ q" && kill $$ ;}'
  - ./test/test-ready.sh
