sudo: required

language: bash

services:
  - docker

env:
  - BOOTKUBE_CONF_NETWORK_PROVIDER=--network-provider=flannel TRAVIS_HAS_HOSTPORT=1
#  - BOOTKUBE_CONF_NETWORK_PROVIDER=--network-provider=experimental-canal
  - BOOTKUBE_CONF_NETWORK_PROVIDER=--network-provider=experimental-calico

before_script:
  - sudo curl -sSL --fail https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
  - sudo chmod +x /usr/local/bin/kubectl
  - env | grep 'BOOTKUBE_CONF_NETWORK_PROVIDER\|TRAVIS' > travis.env
  - export KUBECONFIG=$(pwd)/data/kubeconfig
  - docker-compose -f docker-compose.yaml -f docker-compose.travis.yaml build

script:
  - docker-compose -f docker-compose.yaml -f docker-compose.travis.yaml up -d --scale node=0
  - docker-compose exec master wait-for-bootkube-ready.sh
  - ./test/test-worker-scale.sh
  - ./test/test-pod.sh
  - ./test/test-service.sh

after_script:
  - docker-compose -f docker-compose.yaml -f docker-compose.travis.yaml down -v
