sudo: required

language: bash

services:
  - docker

before_script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose exec master wait-for-bootkube-ready.sh

script:
  - ./test/test-ready.sh
  - ./test/test-pod.sh
