version: '2'

services:
  k8s-master:
    volumes:
      # for dev
      - ./k8s-master/container/etc/systemd/system/kubelet.service:/etc/systemd/system/kubelet.service:ro
      - ./k8s-master/container/usr/local/bin/boot-k8s.sh:/usr/local/bin/boot-k8s.sh:ro
      - ./k8s-master/container/usr/local/bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
      - ./k8s-master/container/usr/local/bin/kubelet-wrapper.sh:/usr/local/bin/kubelet-wrapper.sh:ro

  # repeat for each additional worker node
  k8s-node:
    volumes:
      # for dev
      - ./k8s-master/container/etc/systemd/system/kubeconfig.service:/etc/systemd/system/kubeconfig.service:ro
      - ./k8s-master/container/etc/systemd/system/kubelet.service:/etc/systemd/system/kubelet.service:ro
      - ./k8s-master/container/usr/local/bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
