version: '2'

# docker-machine create -d vmwarefusion --vmwarefusion-cpu-count=2 --vmwarefusion-disk-size=40000 --vmwarefusion-memory-size=2048 k8
# eval $(docker-machine env k8)
# KUBECONFIG=$(pwd)/data/kubeconfig kubectl get nodes
services:
  k8s-master:
    build:
      context: ./k8s-master
    hostname: k8s-master
    working_dir: /data
    tty: true
    privileged: true
    security_opt:
      - seccomp=unconfined
    environment:
      - K8S_MASTER_NODE=1
    ports:
      - 6443:6443
    volumes:
      # for setting up systemd host mounts
      - /:/host
      # for setting up bootkube's auto host kubeconfig
      - /var/run/docker.sock:/mnt/HOST_DOCKER.sock
      # for systemd
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # for dind
      - mnt-share-data:/mnt/share/data:rw
      - var-lib-docker:/var/lib/docker:rw
      # outside data dir access
      - ./data:/data
      # for dev
      - ./k8s-master/container/etc/systemd/system/kubelet.service:/etc/systemd/system/kubelet.service:ro
      - ./k8s-master/container/etc/.overlay:/etc/.overlay:ro
      - ./k8s-master/container/usr/local/bin/boot-k8s.sh:/usr/local/bin/boot-k8s.sh:ro
      - ./k8s-master/container/usr/local/bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
      - ./k8s-master/container/usr/local/bin/kubelet-wrapper.sh:/usr/local/bin/kubelet-wrapper.sh:ro
    tmpfs:
      - /run
      - /run/lock

  # repeat for each additional worker node
  k8s-node-1:
    build:
      context: ./k8s-master
    hostname: k8s-node-1
    working_dir: /data
    tty: true
    privileged: true
    security_opt:
      - seccomp=unconfined
    volumes:
      # for systemd
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # for dind
      - mnt-share-data:/mnt/share/data:rw
      - var-lib-docker-n1:/var/lib/docker:rw
      # outside data dir access
      - ./data:/data
      # for dev
      - ./k8s-master/container/etc/systemd/system/kubeconfig.service:/etc/systemd/system/kubeconfig.service:ro
      - ./k8s-master/container/usr/local/bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
    tmpfs:
      - /run
      - /run/lock

volumes:
  var-lib-docker:
  var-lib-docker-n1:
  mnt-share-data:
