version: '2'

# docker-machine create -d vmwarefusion --vmwarefusion-cpu-count=2 --vmwarefusion-disk-size=40000 --vmwarefusion-memory-size=2048 k8
# eval $(docker-machine env k8)
# KUBECONFIG=$(pwd)/data/kubeconfig kubectl get nodes
services:
  # each additional type of node type can simply extend this (see master node)
  node:
    build:
      context: ./k8s-master
    working_dir: /data
    tty: true
    privileged: true
    security_opt:
      - seccomp=unconfined
    environment:
      - HYPERKUBE_IMAGE_TAG=v1.8.0_coreos.0
    volumes:
      # for setting up bootkube's auto host kubeconfig and getting container info
      - /var/run/docker.sock:/mnt/HOST_DOCKER.sock
      # for systemd
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # for sharing data between containers
      - mnt-share-data:/mnt/share/data:rw
      # outside data dir access
      - ./data:/data
    tmpfs:
      - /run
      - /run/lock

  master:
    extends:
      service: node
    environment:
      - K8S_MASTER_NODE=1
      - BOOTKUBE_IMAGE_TAG=v0.7.0
      - BOOTKUBE_CONF_NETWORK_PROVIDER=--network-provider=experimental-calico
    ports:
      - 6443:6443

  # running instance of etcd because etcd operator has issues with durability
  # @see https://github.com/coreos/etcd-operator/issues/1323
  etcd1:
    image: quay.io/coreos/etcd:v3.2.8
    environment:
      ETCD_NAME: infra1
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd1:2380
      ETCD_INITIAL_CLUSTER: infra1=http://etcd1:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-kube-01
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_DATA_DIR: /data
    volumes:
      - etcd-data:/data

volumes:
  mnt-share-data:
  etcd-data:
