version: '2'

# https://github.com/Mirantis/kubeadm-dind-cluster
# docker-machine create -d vmwarefusion --vmwarefusion-cpu-count=2 --vmwarefusion-disk-size=40000 --vmwarefusion-memory-size=2048 k8
# eval $(docker-machine env k8)
# kubectl --server $(docker-machine ip k8):8080
services:
  k8s-master:
    build:
      context: ./k8s
    working_dir: /data
    tty: true
    privileged: true
#    network_mode: host
    security_opt:
      - seccomp=unconfined
    ports:
      - 6443:6443
    volumes:
      # outside data dir access
      - ./data:/data
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - var-lib-docker:/var/lib/docker:rw
      - ./k8s/container/etc/systemd/system/kubelet.service:/etc/systemd/system/kubelet.service:ro
      - ./abc.sh:/abc.sh:ro
    tmpfs:
      - /run
      - /run/lock

volumes:
  var-lib-docker:
